// dummy_reports.js
const dummyReports = [
  {
    fecha: "28/09/2024",
    hora: "HORA 14:00 PM",
    sucursal: "SUC.G.LAFE",
    marcador: "MARCADOR 1",
    sexo: "NN MASCULINO",
    descripcion:
      "ESTATURA = 1.85 MTS - CAUCASICO - CABELLO CORTO - PERMANECE EN LA FILA - SACA NUMERO DE ATENCION A CLIENTE Y NO OPERA - PERMANECE EN LOBBY DE ATENCION AL CLIENTE - SE RETIRA LUEGO QUE UN CLIENTE HACE UNA EXTRACCION - SE ESTACIONA EN ZONA BANCARIA, FILMA Y OBTIENE IMAGENES A DISCRECION - LA TEMPERATURA ES DE 32º POR LO QUE LLEVAR PUESTA UNA CAMPERA SIGNIFICARIA QUE PODRIA ESTAR OCULTANDO ALGO, PODRIA CONSIDERARSE ARMADO Y PELIGROSO.",
  },
];

export default dummyReports;
